### ISSUE TITLE
Docker ?

### ISSUE THREAD

**Issue by dim6003** [destroyedlolo/Marcel#22]
Hi,
Nice project, have looking for a quite some time hoq to integrate my Ha7net (1-wire) devices to mqtt.
what about a docker package, with docker-compose section example ? 
Thanks !

**Comment by destroyedlolo** [comment]
Hello,

Unfortunately, no docker-compose available, even if it's not very complicated to build one. 

But for your usage, it will not help as such : for 1-wire, Marcel is expecting probes to be exposed as virtual files where Ha7net exposes only http interface. So it can use it as such.

If you really want to use Marcel as a bridge for your device, you'll have to create some Lua scripts to query probes' URL and then publish the result. But tools like Majordome are more suitable.

Best regards

Laurent

**Comment by destroyedlolo** [comment]
Perhasp for the future if I have many requests or the need, but for the moment, I don't have the time.
Contribution will be welcome, obviously, if someone wants to create one.

**Comment by dim6003** [comment]
> But for your usage, it will not help as such : for 1-wire, Marcel is expecting probes to be exposed as virtual files where Ha7net exposes only http interface. So it can use it as such.
> 
> If you really want to use Marcel as a bridge for your device, you'll have to create some Lua scripts to query probes' URL and then publish the result. But tools like Majordome are more suitable.

Was just planning to use OWFS in between, which knows how to interface to HA7-net.

**Comment by destroyedlolo** [comment]
Ha ok, I wasn't aware about such bridging with OWFS (as I don't own such device :) ) : interesting.
Which settings are U using ?

About the installation : even if there is no docker image yet, the installation is very straight forward.
More or less :
- compilation chain
- PahoC (if not packaged within your flavor, it's the only component which is needing a particular attention as the Paho installation script is not very smart)
- other dependencies.
- LFMakeMaker
- customize remake.sh (to enable/disable modules compilation)
- make
- install

I did the installation on Gentoo, Arch, Debian/Ubuntu and it takes to me about 15 minutes :)

**Comment by dim6003** [comment]
In owfs.conf:
`server: HA7= 192.168.48.99`

Never compiled for docker up to now. will give it a try when i find some time. Docker instance on intel i5 computer running ubuntu 22.04.
I was more asking for docker-compose example, and overall configuration requirements.

**Comment by destroyedlolo** [comment]
It's not for docker compilation, it's to compile it on your Ubuntu host.
And as Ubuntu is Debian derivate, you have follow step by step **Build from source.md** procedure to get Marcel installed.

**Comment by destroyedlolo** [comment]
No news ... good news.
